dev:
  level:      "DEBUG"
  email:      "errors@zwartopwit.be"
  from:       "noreply@zwartopwit.be"
  subject:    "AppTools Error"
  smtp:       "mail.bulckens.com"
  port:       "465"
  username:   "errors@zwartopwit.be"
  password:   "[D>pTF93]#Jwb33ER9"
  encryption: "ssl"
  theme:
    body:     "#aaaaaa"
    item:     "#bbbbbb"
    link:     "#cccccc"
    text:     "#dddddd"
    title:    "#eeeeee"
    class:    "#ffffff"
    function: "#999999"
    line:     "#888888"