dev:
  level:      "custom"
  email:      "custom"
  from:       "custom"
  subject:    "custom"
  smtp:       "custom"
  port:       "custom"
  username:   "custom"
  password:   "custom"
  encryption: "custom"